### ISSUE TITLE
Kernel 5.10 breaks build

### ISSUE THREAD

**Issue by gordboy** [gordboy/rtl8812au-5.9.3.2#1]
Currently testing kernel 5.10-rc5 and it breaks the build with errors relating to `get_fs`, `set_fs` and friends in

```
os_dep/osdep_service.c
os_dep/linux/os_intfs.c
core/rtw_wlan_util.c
core/rtw_btcoex.c
```

Turns out this is a known thing in KernelLand and they wanted to get rid of it for ages, and finally actually did it, for some architectures at least.

http://lkml.iu.edu/hypermail/linux/kernel/2010.3/00552.html
https://lwn.net/Articles/832121/
https://lwn.net/Articles/722267/

In the Realtek code, the main use goes something like this -

```
oldfs = get_fs();      // Save old boundary
set_fs(KERNEL_DS);     // Set new boundary
STUFF;                 // Some sort of read, copy or move
set_fs(oldfs);         // Restore old boundary
```

I will look at this over the next while and try to figure out a clean, minimal fix.

**Comment by morrownr** [comment]
I noticed that RinCat has applied a k5.10 fix to:  https://github.com/RinCat/RTL88x2BU-Linux-Driver

I also maintain a driver for the 88x2bu so I keep a watch on repos that seem to do a good job. I haven't really looked at this subject in depth yet as I am busy trying to bring two additional drivers, 8814au and 8821au, online and the 8814au is a challenge. If you run onto a 8814au driver that is from this year, let me know.

**Comment by gordboy** [comment]
I did think about the RinCat idea of just excising the whole thing for kernels >= 5.10, but I decided it might break things. Now I am going to revisit that idea, since someone else did it. It also has the great benefit of being quasi-biblical

`"if thine eye offends thee, then strike it out".`

As for other devices like 8814au, well I will let you know if I see anything.

**Comment by morrownr** [comment]
I took a look at what RinCat did and I had the same thought as you. I haven't researched it further due to higher priorities but since we are discussing it...

The ability to just cut out the now non-existent kernel function calls must indicate that there is now an "autopilot" type of system that handles the job without the need for programmers to make the calls. Do you see any other way to explain it? There is a big question is my mind relating to the different platforms. Since the dropped kernel functions are being cut for different platforms at different times, how is that going to be handled?

One of my test systems is a Raspberry Pi 4B running Raspberry Pi OS 32 bit. It is already running k5.10 rc5. I've been testing my repos on it this week and everything works well with no fix for k5.10. That tells me that ARM has not undergone the exorcism yet which, I guess, means that it will happen in a future kernel which leads to the questions about how we will handle this on different platforms. This sounds messy.

**Comment by gordboy** [comment]
So I decided to give the RinCat solution a go. Everything went well until the build failed on the very last step, converting the 8812.o to 8812.ko. It all worked for 5.4, 5.8, 5.9 but not 5.10.

Not sure if that is a Realtek thing or a kernel thing. Anyways I decided to step back and take a rest.

Something I will definitely be looking at is dynamic LED switching by writing to a file in /proc/... which I wrote for my 5.2.20.2 repo. I decided not to bother with that for 5.6.4.2 because someone wrote an alternative for the aircrack repo, and I could not be bothered to unpick the code. But it is time it was brought back from the dead ...

Take care my friend.

**Comment by gordboy** [comment]
There are bug reports to Debian & Ubuntu (that I know about) regarding the breakage of out-of-tree modules in 5.10-rcN. Hopefully this will be resolved before 5.10 reaches final release.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975571
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1906072

I had a rest and then decided to fix up the broken 5.10rc-5 kernel tree ... I managed to copy and rename a script from kernel 5.4 and drop it into the kernel headers ...

So this RinCat thing actually works fine. But I am not sure if the code would break if it ever executed the sections that have been changed. There are only a few functions that needed changing, and it could well be that they are not ever called in the normal course of operation.

Anyways, I will add tracing code to those sections, and see if they ever are called. Obviously if they are never called that leaves the question of whether the changes are sound or just plain lucky unresolved.

And if they are called, it still might be pure luck ... haha. Anyways, for now it is the only fix around.

And now time for that actual break from all this kernel malarkey :)

**Comment by RinCat** [comment]
Linux `kernel_write` and `kernel_read` should automatic handle that, which should be safe remove `set_fs`. If you read and compare 5.9 and 5.10 kernel sources.

`sock_sendmsg` and the `msg` seems already in kernel space, and all the usages are not support (comment out by realtek). I don't see any function can call it.

**Comment by gordboy** [comment]
Thanks for that @RinCat. I did some code tracing and I largely agree.

`"Seek and ye shall find".`

Also I left a dongle running all night and it did not break anything, so I think you are right. Either the code is safe, or never gets called.

`"Ask and ye shall receive".`

I might get around to doing all this by the suggested `iov_iter` method, just in case this all comes back to haunt me. And in any case kernel 5.10 is not quite ready for public use, so there is no rush.

So for now, I am sanguine and serene.

**Comment by RinCat** [comment]
`kernel_write` and `kernel_read` already using `iov_iter`, so you don't need to do anything.
https://github.com/torvalds/linux/blob/c84e1efae022071a4fcf9f1899bf71777c49943a/fs/read_write.c#L453-L454
https://github.com/torvalds/linux/blob/c84e1efae022071a4fcf9f1899bf71777c49943a/fs/read_write.c#L549-L550

**Comment by gordboy** [comment]
Good work !
