### ISSUE TITLE
Dont Compile on Linux 5.11

### ISSUE THREAD

**Issue by Optivan** [gordboy/rtl8812au-5.9.3.2#10]
Hi i try to Compile on Ubuntu 18.04 with Kernel 5.11, but didn't work.

**Comment by JHM-O** [comment]
Hi, same story overhere. Code won't compile on Debian Bullseye/Sid and 5.11 kernel

**Comment by Optivan** [comment]
So after going to Work and came Back Home heres whats Happen.

make[1]: Verzeichnis „/usr/src/linux-headers-5.11.0-generic“ wird betreten
  CC [M]  /home/optivan/.rtl/core/rtw_cmd.o
  CC [M]  /home/optivan/.rtl/core/rtw_security.o
  CC [M]  /home/optivan/.rtl/core/rtw_debug.o
  CC [M]  /home/optivan/.rtl/core/rtw_io.o
  CC [M]  /home/optivan/.rtl/core/rtw_ioctl_query.o
  CC [M]  /home/optivan/.rtl/core/rtw_ioctl_set.o
  CC [M]  /home/optivan/.rtl/core/rtw_ieee80211.o
  CC [M]  /home/optivan/.rtl/core/rtw_mlme.o
  CC [M]  /home/optivan/.rtl/core/rtw_mlme_ext.o
  CC [M]  /home/optivan/.rtl/core/rtw_mi.o
  CC [M]  /home/optivan/.rtl/core/rtw_wlan_util.o
  CC [M]  /home/optivan/.rtl/core/rtw_vht.o
  CC [M]  /home/optivan/.rtl/core/rtw_pwrctrl.o
  CC [M]  /home/optivan/.rtl/core/rtw_rf.o
  CC [M]  /home/optivan/.rtl/core/rtw_chplan.o
  CC [M]  /home/optivan/.rtl/core/monitor/rtw_radiotap.o
  CC [M]  /home/optivan/.rtl/core/rtw_recv.o
  CC [M]  /home/optivan/.rtl/core/rtw_sta_mgt.o
  CC [M]  /home/optivan/.rtl/core/rtw_ap.o
  CC [M]  /home/optivan/.rtl/core/mesh/rtw_mesh.o
  CC [M]  /home/optivan/.rtl/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /home/optivan/.rtl/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /home/optivan/.rtl/core/rtw_xmit.o
  CC [M]  /home/optivan/.rtl/core/rtw_p2p.o
  CC [M]  /home/optivan/.rtl/core/rtw_rson.o
  CC [M]  /home/optivan/.rtl/core/rtw_tdls.o
  CC [M]  /home/optivan/.rtl/core/rtw_br_ext.o
  CC [M]  /home/optivan/.rtl/core/rtw_iol.o
  CC [M]  /home/optivan/.rtl/core/rtw_sreset.o
  CC [M]  /home/optivan/.rtl/core/rtw_btcoex_wifionly.o
  CC [M]  /home/optivan/.rtl/core/rtw_btcoex.o
  CC [M]  /home/optivan/.rtl/core/rtw_beamforming.o
  CC [M]  /home/optivan/.rtl/core/rtw_odm.o
  CC [M]  /home/optivan/.rtl/core/rtw_rm.o
  CC [M]  /home/optivan/.rtl/core/rtw_rm_fsm.o
  CC [M]  /home/optivan/.rtl/core/rtw_rm_util.o
  CC [M]  /home/optivan/.rtl/core/efuse/rtw_efuse.o
  CC [M]  /home/optivan/.rtl/core/crypto/aes-internal.o
  CC [M]  /home/optivan/.rtl/core/crypto/aes-internal-enc.o
  CC [M]  /home/optivan/.rtl/core/crypto/aes-gcm.o
  CC [M]  /home/optivan/.rtl/core/crypto/aes-ccm.o
  CC [M]  /home/optivan/.rtl/core/crypto/aes-omac1.o
  CC [M]  /home/optivan/.rtl/core/crypto/ccmp.o
  CC [M]  /home/optivan/.rtl/core/crypto/gcmp.o
  CC [M]  /home/optivan/.rtl/core/crypto/aes-siv.o
  CC [M]  /home/optivan/.rtl/core/crypto/aes-ctr.o
  CC [M]  /home/optivan/.rtl/core/crypto/sha256-internal.o
  CC [M]  /home/optivan/.rtl/core/crypto/sha256.o
  CC [M]  /home/optivan/.rtl/core/crypto/sha256-prf.o
  CC [M]  /home/optivan/.rtl/core/crypto/rtw_crypto_wrap.o
  CC [M]  /home/optivan/.rtl/core/rtw_swcrypto.o
  CC [M]  /home/optivan/.rtl/os_dep/osdep_service.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/os_intfs.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/usb_intf.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/usb_ops_linux.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/ioctl_linux.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/xmit_linux.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/mlme_linux.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/recv_linux.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/wifi_regd.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/rtw_android.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/rtw_proc.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/rtw_rhashtable.o
  CC [M]  /home/optivan/.rtl/os_dep/linux/ioctl_mp.o
  CC [M]  /home/optivan/.rtl/hal/hal_intf.o
  CC [M]  /home/optivan/.rtl/hal/hal_com.o
  CC [M]  /home/optivan/.rtl/hal/hal_com_phycfg.o
  CC [M]  /home/optivan/.rtl/hal/hal_phy.o
  CC [M]  /home/optivan/.rtl/hal/hal_dm.o
  CC [M]  /home/optivan/.rtl/hal/hal_dm_acs.o
  CC [M]  /home/optivan/.rtl/hal/hal_btcoex_wifionly.o
  CC [M]  /home/optivan/.rtl/hal/hal_btcoex.o
  CC [M]  /home/optivan/.rtl/hal/hal_mp.o
  CC [M]  /home/optivan/.rtl/hal/hal_mcc.o
/home/optivan/.rtl/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_ch_switch_notify’:
/home/optivan/.rtl/os_dep/linux/ioctl_cfg80211.c:459:3: error: too few arguments to function ‘cfg80211_ch_switch_started_notify’
   cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef, 0);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/optivan/.rtl/include/osdep_service_linux.h:98:0,
                 from /home/optivan/.rtl/include/osdep_service.h:53,
                 from /home/optivan/.rtl/include/drv_types.h:27,
                 from /home/optivan
/.rtl/os_dep/linux/ioctl_cfg80211.c:17:
./include/net/cfg80211.h:7585:6: note: declared here
 void cfg80211_ch_switch_started_notify(struct net_device *dev,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /home/optivan/.rtl/hal/hal_hci/hal_usb.o
  CC [M]  /home/optivan/.rtl/hal/led/hal_led.o
  CC [M]  /home/optivan/.rtl/hal/led/hal_usb_led.o
  CC [M]  /home/optivan/.rtl/hal/HalPwrSeqCmd.o
  CC [M]  /home/optivan/.rtl/hal/rtl8812a/Hal8812PwrSeq.o
  CC [M]  /home/optivan/.rtl/hal/rtl8812a/Hal8821APwrSeq.o
  CC [M]  /home/optivan/.rtl/hal/rtl8812a/rtl8812a_xmit.o
  CC [M]  /home/optivan/.rtl/hal/rtl8812a/rtl8812a_sreset.o
  CC [M]  /home/optivan/.rtl/hal/rtl8812a/rtl8812a_hal_init.o
scripts/Makefile.build:279: recipe for target '/home/optivan/.rtl/os_dep/linux/ioctl_cfg80211.o' failed
make[2]: *** [/home/optivan/.rtl/os_dep/linux/ioctl_cfg80211.o] Error 1
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
Makefile:1800: recipe for target '/home/optivan/.rtl' failed
make[1]: *** [/home/optivan/.rtl] Error 2
make[1]: Verzeichnis „/usr/src/linux-headers-5.11.0-generic“ wird verlassen
Makefile:2362: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by javiercbk** [comment]
I've created a PR. To quickly patch this you can change `ioctl_cfg80211.c` line 459.

```c
cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef, 0, false);
```

The full explaination on this change can be reviewed in the PR linked to this issue

**Comment by JHM-O** [comment]
Thanks mate,

Works.

**Comment by iamdegenerat3** [comment]
> I've created a PR. To quickly patch this you can change `ioctl_cfg80211.c` line 459.
> 
> ```c
> cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef, 0, false);
> ```
> 
> The full explaination on this change can be reviewed in the PR linked to this issue

works just fine. thanks man

**Comment by gordboy** [comment]
Guys, see the comment in the PR at https://github.com/gordboy/rtl8812au-5.9.3.2/pull/11#issuecomment-788819753

You cannot just make changes like that without wrapping them properly in preprocessor directives to ensure that it still compiles for different kernel versions.

I like the change (provided it actually works) and if @javiercbk  amends their PR, I will take it in, subject to my own testing.

**Comment by gordboy** [comment]
Today is officially my day for making typos ... all corrected ... thus far

**Comment by gordboy** [comment]
Fix now implemented thanks guys.
