### ISSUE TITLE
Cannot bring device up -- Operation not permitted

### ISSUE THREAD

**Issue by chytzkoi** [gordboy/rtl8812au-5.9.3.2#12]
Hi, 

I have an issue with specific device  7392:a812 Edimax Technology Co., Ltd **Edimax AC600 USB**. Firstly noticed on my router which is running Gentoo linux and there I have already running for two months  the 0bda:8812 Realtek Semiconductor Corp. **RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter**. I plugged the Edimax one and it refused to be brought up. So I plugged in my debian laptop cloned the repo fresh and installed the module with same results. Is there anything else which I would be able to try to find the issue?

I have attached
[rtl8812au_edimax_issue_01.txt](https://github.com/gordboy/rtl8812au-5.9.3.2/files/6097180/rtl8812au_edimax_issue_01.txt)
 detailed info. Basically it boils down to this

```
#ip link set up dev wlx00e04c1cd536
RTNETLINK answers: Operation not permitted
```

Basic info for Debian laptop:
```
root@host:/home/user/tarballs/rtl8812au-5.9.3.2# uname -a
Linux host 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux
root@host:/home/user/tarballs/rtl8812au-5.9.3.2# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

Basic info for Gentoo router/laptop:
```
$ uname -a
Linux kvm 5.4.80-gentoo-r1-x86_64 #1 SMP Sun Jan 10 17:33:19 CET 2021 x86_64 Intel(R) Core(TM) i5 CPU M 520 @ 2.40GHz GenuineIntel GNU/Linux
```

**Comment by gordboy** [comment]
Are you sure you have the right command there?

I thought it was something like

```
ip link set wlx00e04c1cd536 up
```

 Anyways it all should work, according to other users.
