### ISSUE TITLE
compiling on cubietruck

### ISSUE THREAD

**Issue by Simon566** [gordboy/rtl8812au-5.9.3.2#14]
Hi,

im using the switch CONFIG_PLATFORM_ARM_RPI = y , and i fail compiling by:

 CC [M]  /root/rtl8812au-5.9.3.2/platform/platform_ops.o
  CC [M]  /root/rtl8812au-5.9.3.2/core/rtw_mp.o
  LD [M]  /root/rtl8812au-5.9.3.2/8812au.o
ld: cannot find /root/rtl8812au-5.9.3.2/core/rtw_cmd.o: No such file or directory
make[2]: *** [scripts/Makefile.build:430: /root/rtl8812au-5.9.3.2/8812au.o] Error 1
make[1]: *** [Makefile:1803: /root/rtl8812au-5.9.3.2] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.21-sunxi'
make: *** [Makefile:2362: modules] Error 2
root@cubietruck:~/rtl8812au-5.9.3.2

 a subsequent make gives this:

root@cubietruck: /rtl8812au-5.9.3.2 make
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.10.21-sunxi/build M=/root/rtl8812au-5.9.3.2  modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.21-sunxi'
  CC [M]  /root/rtl8812au-5.9.3.2/core/rtw_cmd.o
  LD [M]  /root/rtl8812au-5.9.3.2/8812au.o
  MODPOST /root/rtl8812au-5.9.3.2/Module.symvers
make[3]: *** No rule to make target '/root/rtl8812au-5.9.3.2/8812au.mod.o', needed by '/root/rtl8812au-5.9.3.2/8812au.ko'.  Stop.
make[2]: *** [scripts/Makefile.modpost:117: __modpost] Error 2
make[1]: *** [Makefile:1707: modules] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.21-sunxi'
make: *** [Makefile:2362: modules] Error 2
root@cubietruck:~/rtl8812au-5.9.3.2#

can you take a look ? on my x86 Odroid H2 your module compiles fine, but the cubietruck fails.

regards,
Simon

**Comment by Simon566** [comment]
a subsequent make give s me this:
  CC [M]  /root/rtl8812au-5.9.3.2/core/rtw_mp.o
  LD [M]  /root/rtl8812au-5.9.3.2/8812au.o
ld: cannot find /root/rtl8812au-5.9.3.2/core/rtw_cmd.o: No such file or directory
make[2]: *** [scripts/Makefile.build:430: /root/rtl8812au-5.9.3.2/8812au.o] Error 1
make[1]: *** [Makefile:1803: /root/rtl8812au-5.9.3.2] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.21-sunxi'
make: *** [Makefile:2362: modules] Error 2
root@cubietruck:~/rtl8812au-5.9.3.2# make
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.10.21-sunxi/build M=/root/rtl8812au-5.9.3.2  modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.21-sunxi'
  CC [M]  /root/rtl8812au-5.9.3.2/core/rtw_cmd.o
  LD [M]  /root/rtl8812au-5.9.3.2/8812au.o
  MODPOST /root/rtl8812au-5.9.3.2/Module.symvers
make[3]: *** No rule to make target '/root/rtl8812au-5.9.3.2/8812au.mod.o', needed by '/root/rtl8812au-5.9.3.2/8812au.ko'.  Stop.
make[2]: *** [scripts/Makefile.modpost:117: __modpost] Error 2
make[1]: *** [Makefile:1707: modules] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.21-sunxi'
make: *** [Makefile:2362: modules] Error 2
root@cubietruck:~/rtl8812au-5.9.3.2#

**Comment by gordboy** [comment]
I really have no idea about RPI, sorry.

But I would try turning off all other ARCH flags.

**Comment by Simon566** [comment]
Hi ,

its possible to use x86 as compile target on cubietruck, you need to change the float-hard option but apart from this it works

regards,
Simon

**Comment by gordboy** [comment]
All good then. I will close this issue. Thanks for letting me know.
