### ISSUE TITLE
Driver does not load/activate on USB TP-link AC600 Archer T2Uv3 (2357:011f)

### ISSUE THREAD

**Issue by gatopeich** [gordboy/rtl8812au-5.9.3.2#15]
Hello, I am using TP-link AC600 Archer T2Uv3 (2357:011f) with the driver version 5.6.4.2 from [aircrack-ng/rtl8812au](https://github.com/aircrack-ng/rtl8812au)

After removing v5.6 and installing this one (5.9.3.2), the driver does not load automatically. If loaded with modprobe it does nothing.
I have tried all combinations of installing/uninstalling both versions, the only one that loads for my USB dongle is 5.6.

**Comment by gordboy** [comment]
The device ID for your Archer is not in the code. And I think it is a RTL8821AU rather than a RTL8812AU. This driver only supports 8812.

**Comment by gatopeich** [comment]
Thanks. I will try adding the ID and let u know if it works.

**Comment by mad-max-66** [comment]
I try today with git clone.... but not work.
`[  726.187339] usb 2-1.1: new high-speed USB device number 8 using ehci-pci
[  726.296611] usb 2-1.1: New USB device found, idVendor=2357, idProduct=011f, bcdDevice= 2.00
[  726.296620] usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  726.296625] usb 2-1.1: Product: 802.11ac WLAN Adapter 
[  726.296628] usb 2-1.1: Manufacturer: Realtek 
[  726.296632] usb 2-1.1: SerialNumber: 00e04c000001
[  748.492870] usb 2-1.1: USB disconnect, device number 8
[  759.721846] usb 2-1.1: new high-speed USB device number 9 using ehci-pci
[  759.831011] usb 2-1.1: New USB device found, idVendor=2357, idProduct=011f, bcdDevice= 2.00
[  759.831019] usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  759.831024] usb 2-1.1: Product: 802.11ac WLAN Adapter 
[  759.831028] usb 2-1.1: Manufacturer: Realtek 
[  759.831031] usb 2-1.1: SerialNumber: 00e04c000001
dmesg only this
_____________________________________
Forgive me but in this file I cannot find the id of the device in question ...https://github.com/gordboy/rtl8812au-5.9.3.2/blob/main/os_dep/linux/usb_intf.c

**Comment by gordboy** [comment]
Guys. This repo is for 8812AU only.

The 2357:011f device is 8821, and therefore not supported. I know other repos might support this, but mine does not.

You might try

https://github.com/morrownr/8812au

**Comment by zeph** [comment]
trying out github.com/aircrack-ng/rtl8812au.git ...works
