### ISSUE TITLE
doesn't compile on kernel 5.12

### ISSUE THREAD

**Issue by JHM-O** [gordboy/rtl8812au-5.9.3.2#17]
Hi,

Again an error on kernel-update, to 5.12. Below the error-report.

DKMS make.log for rtl8812au-5.9.3.2 for kernel 5.12.0 (x86_64)
Mon 26 Apr 2021 14:28:54 CEST
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.12.0/build M=/var/lib/dkms/rtl8812au/5.9.3.2/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.12.0'
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_chplan.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/monitor/rtw_radiotap.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/mesh/rtw_mesh.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_rson.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_rm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_rm_fsm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_rm_util.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/aes-internal.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/aes-internal-enc.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/aes-gcm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/aes-ccm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/aes-omac1.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/ccmp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/gcmp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/aes-siv.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/aes-ctr.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/sha256-internal.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/sha256.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/sha256-prf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/crypto/rtw_crypto_wrap.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/core/rtw_swcrypto.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/osdep_service.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/os_intfs.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/usb_intf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/usb_ops_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/ioctl_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/xmit_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/mlme_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/recv_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/ioctl_cfg80211.o
/var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/recv_linux.c: In function ‘napi_recv’:
/var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/recv_linux.c:358:55: error: ‘GRO_DROP’ undeclared (first use in this function)
  358 |    if (rtw_napi_gro_receive(&padapter->napi, pskb) != GRO_DROP)
      |                                                       ^~~~~~~~
/var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/recv_linux.c:358:55: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:271: /var/lib/dkms/rtl8812au/5.9.3.2/build/os_dep/linux/recv_linux.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1851: /var/lib/dkms/rtl8812au/5.9.3.2/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.12.0'
make: *** [Makefile:2362: modules] Error 2

Tia for any suggestions on this.

**Comment by gordboy** [comment]
Here's a suggestion -

stop installing kernels that have only been out for 2 days, and expecting everything to just work ... just about every time a new kernel comes out, I have to patch the code to make it work again.

A fix will be available soon, once I get a decent development platform for the new kernel.

Thank you for your patience.

**Comment by gordboy** [comment]
You can thank @morrownr for my fix, based on

https://github.com/morrownr/8812au/commit/fcb0343c52daa647150f027258958194824e2ace

as you can see we have been discussing this for a while, but since the new kernel was not ready for deployment, I held back. Plus this all has to be tested. Fix now incorporated.

**Comment by JHM-O** [comment]
Well, a big thank you to you both. Much appreciation for  your work.
And I will bear in mind your age when new issues emerge.

With kind greetings.

**Comment by morrownr** [comment]
gordboy,

I cannot understand why you don't have this driver ready for and tested on 5.13. You are slacking again.

...ducking and running...

**Comment by gordboy** [comment]
If it wasn't for those pesky kids, I would have gotten clean away with it :)
