### ISSUE TITLE
5GHz Channels 52-140

### ISSUE THREAD

**Issue by kabati-ops** [gordboy/rtl8812au-5.9.3.2#18]
Hi gordboy,

I just installed your driver on Ubuntu 20.04 and it works fine. Thanks a lot!

But, my router has DFS - Dynamic Frequency Search.
Therefore it uses the 5 GHz channels above 48 (52-140).
The rtl8812au is able, too, to use this channels.
Are you planning to add them? 

PS: Sorry, I'm not a native english speaker.

**Comment by kabati-ops** [comment]
Sorry, no issue. I found the solution.

echo "options 8812au rtw_country_code=DE" | sudo tee /etc/modprobe.d/8812au_options.conf

**Comment by gordboy** [comment]
Yes I thought there was something amiss because I use channels 100+104+108+112 or something similar, to keep far from the madding crowd ...

... anyways thanks for answering yourself, because someone else might find your solution useful :)
