### ISSUE TITLE
My testing so far shows this 5.9.3.2 version to be the most solid version of the driver yet...

### ISSUE THREAD

**Issue by morrownr** [gordboy/rtl8812au-5.9.3.2#2]
gordboy,

Have you had time to test much? Here are my thoughts so far:

- Very clean install once we patched that one compiler complaint.
- It is nice to have code that is patched all the through 5.8 by Realtek.
- I've tested and show a performance pickup vs previous versions.
- dmesg is clean.

Best code release I've ever seen from Realtek.

**Comment by usama7628674** [comment]
But still no support for Virtual Interface.

**Comment by gordboy** [comment]
The code does seem to be better than usual. But it is early days. There are undoubtedly some pitfalls ahead.

**Comment by morrownr** [comment]
I'm sure we will find some issues. One thing I noticed today when doing some controlled testing is that my 8812bu adapter is averaging about 560 Mbits/sec per iperf3 while my 8812au adapter is only averaging about 472 Mbits/sec. The test was carefully controlled as both devices were hooked up to the same computer pulling from the same router. Interestingly enough, the previous version of the 8812bu driver only showed results of about what we are seeing here with the new 8812au driver. Something happened in the most recent 8812bu driver in that it shows a BIG increase in speed. Maybe it can happen in other drivers as well. The fastest adapter I have is the one based on the 8814au but that is to be expected. Right now I have 4 drivers up with one more coming soon. I'm ready to commit that Virtual Interface code as soon as you are finished with it. <g>

**Comment by usama7628674** [comment]
@morrownr Really?Can you implement virtual interface?This feature has long been missing in almost all realtek drivers.Even the driver [here](https://github.com/aircrack-ng/rtl8812au) does not have this feature,which is most used now.

**Comment by usama7628674** [comment]
Does this https://github.com/morrownr/8812au have virtual interface?

**Comment by usama7628674** [comment]
Without VIF, we couldn't do packet injection and make access point at the same time.I'd be grateful if you commit the code in this repo.

**Comment by morrownr** [comment]
I guess i forgot to add the part about it being a joke in my comment about the virtual interface support. Sorry about that. I'd love for the driver to have that capability but my opinion is that it is a capability that is beyond what us in the community can do given that we do not have all of the information the closed source fw files could provide and even if we had complete information, it would likely be a very large effort which would cause me to ask for a pay raise. Have your looked at using 2 adapters to get this capability? You can easily run multiple wifi adapters on the same system in Linux. I know because I do it.
