### ISSUE TITLE
cannot compile on solus os with the latest kernel

### ISSUE THREAD

**Issue by x0pa** [gordboy/rtl8812au-5.9.3.2#20]
this is the error message i get.

`CC [M]  /home/username/Drivers/rtl8812au-5.9.3.2/os_dep/linux/ioctl_cfg80211.o
/home/username/Drivers/rtl8812au-5.9.3.2/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_ch_switch_notify’:
/home/username/Drivers/rtl8812au-5.9.3.2/os_dep/linux/ioctl_cfg80211.c:459:3: error: too few arguments to function ‘cfg80211_ch_switch_started_notify’
459 |   cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef, 0);
    |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/username/Drivers/rtl8812au-5.9.3.2/include/osdep_service_linux.h:98,
               from /home/username/Drivers/rtl8812au-5.9.3.2/include/osdep_service.h:53,
               from /home/username/Drivers/rtl8812au-5.9.3.2/include/drv_types.h:27,
               from /home/username/Drivers/rtl8812au-5.9.3.2/os_dep/linux/ioctl_cfg80211.c:17:
./include/net/cfg80211.h:7585:6: note: declared here
7585 | void cfg80211_ch_switch_started_notify(struct net_device *dev,
    |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:279: /home/username/Drivers/rtl8812au-5.9.3.2/os_dep/linux/ioctl_cfg80211.o] Error 1
make[1]: *** [Makefile:1820: /home/username/Drivers/rtl8812au-5.9.3.2] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.11.16-178.current'
make: *** [Makefile:2362: modules] Error 2
install -p -m 644 8812au.ko  /lib/modules/5.11.16-178.current/kernel/drivers/net/wireless/
install: cannot stat '8812au.ko': No such file or directory
make: *** [Makefile:2368: install] Error 1
modprobe: WARNING: Module 8812au not found in directory /lib/modules/5.11.16-178.current`

**Comment by gordboy** [comment]
You have an old version of the driver from before kernel 5.11.

It has actually been updated for kernel 5.11 and kernel 5.12 since then, and works very well, with no compile errors whatsoever.

Please download the latest driver version

https://github.com/gordboy/rtl8812au-5.9.3.2/archive/refs/heads/main.zip

or use git to clone the driver, and use `git pull` to keep it updated.

**Comment by x0pa** [comment]
awesome thank you
