### ISSUE TITLE
Unable to build in Ubuntu 18.04 with Kernel 5.11.5

### ISSUE THREAD

**Issue by Illusion-1404** [gordboy/rtl8812au-5.9.3.2#24]
Hi, I am getting this error, while trying to build the driver:- 

My kernel version is : 5.11.5 , kernel headers are installed.

ld:scripts/module.lds:6: ignoring invalid character `#' in expression
ld:scripts/module.lds:6: syntax error
scripts/Makefile.modfinal:58: recipe for target '/home/octo-ws/rtl8812au-5.9.3.2/8812au.ko' failed
make[3]: *** [/home/octo-ws/rtl8812au-5.9.3.2/8812au.ko] Error 1
scripts/Makefile.modpost:117: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 2
Makefile:1710: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.11.5-051105-generic'
Makefile:2362: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by gordboy** [comment]
I have a feeling that the build chain in 18.04 is too old for kernel 5.11 (for this task anyways)

The reason I say that is that it all builds fine on 20.04 and above.

**Comment by gordboy** [comment]
You might find this useful - 

https://github.com/morrownr/USB-WiFi

**Comment by gordboy** [comment]
Not maintaining this repo any further. There are better devices and drivers.
