### ISSUE TITLE
DKMS update failed

### ISSUE THREAD

**Issue by gianmarcogg03** [gordboy/rtl8812au-5.9.3.2#26]
I'm running Arch Linux and after an update my Wi-Fi dongle that uses the rtl8812au driver (installed from the AUR) doesn't work anymore, so I tried to update all of my kernel modules with `sudo dkms autoinstall` and it didn't work. You can read the log file [here](https://github.com/gordboy/rtl8812au-5.9.3.2/files/7143558/log.txt).

**Comment by yichangshengwu** [comment]
working fine on my arch

![截图_2021-09-11_13-16-14](https://user-images.githubusercontent.com/43059917/132937186-3e0a8d83-a39b-495e-a36e-285dfa2fda68.png)

**Comment by gordboy** [comment]
Looks like you have an old version of the driver there. I know virtually nothing about Archlinux but you could try uninstalling the old driver, and reinstalling it, which should update the driver to the latest version.

I should also add that I am not going to be supporting this very much longer and you would be best switching to something from here

https://github.com/morrownr/USB-WiFi

Good luck

**Comment by gianmarcogg03** [comment]
The issue apparently either has to do with my wireless adapter, but I'm now using another adapter so I guess I can close this issue. Thank you for the help.
