### ISSUE TITLE
Ubuntu 20.04.3 Linux Kernel 5.15 Driver not Compiling

### ISSUE THREAD

**Issue by Optivan** [gordboy/rtl8812au-5.9.3.2#27]
Hi today i upgraded my System with 5.15 Kernel but make trows out errors. 
Here is the Log:

 make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.15.0-generic/build M=/home/optivan/.rtl  modules
make[1]: Verzeichnis „/usr/src/linux-headers-5.15.0-generic“ wird betreten
  CC [M]  /home/moneytrail/.rtl/core/rtw_cmd.o
  CC [M]  /home/optivan/.rtl/core/rtw_security.o
  CC [M]  /home/optivan/.rtl/core/rtw_debug.o
  CC [M]  /home/optivan/.rtl/core/rtw_io.o
  CC [M]  /home/optivan/.rtl/core/rtw_ioctl_query.o
  CC [M]  /home/optivan/.rtl/core/rtw_ioctl_set.o
  CC [M]  /home/optivan/.rtl/core/rtw_ieee80211.o
  CC [M]  /home/optivan/.rtl/core/rtw_mlme.o
  CC [M]  /home/optivan/.rtl/core/rtw_mlme_ext.o
  CC [M]  /home/optivan/.rtl/core/rtw_mi.o
  CC [M]  /home/optivan/.rtl/core/rtw_wlan_util.o
  CC [M]  /home/optivan/.rtl/core/rtw_vht.o
  CC [M]  /home/optivan/.rtl/core/rtw_pwrctrl.o
  CC [M]  /home/optivan/.rtl/core/rtw_rf.o
  CC [M]  /home/optivan/.rtl/core/rtw_chplan.o
  CC [M]  /home/optivan/.rtl/core/monitor/rtw_radiotap.o
  CC [M]  /home/optivan/.rtl/core/rtw_recv.o
  CC [M]  /home/optivan/.rtl/core/rtw_sta_mgt.o
  CC [M]  /home/optivan/.rtl/core/rtw_ap.o
  CC [M]  /home/optivan/.rtl/core/mesh/rtw_mesh.o
  CC [M]  /home/optivan/.rtl/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /home/optivan/.rtl/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /home/optivan/.rtl/core/rtw_xmit.o
  CC [M]  /home/optivan/.rtl/core/rtw_p2p.o
  CC [M]  /home/optivan/.rtl/core/rtw_rson.o
  CC [M]  /home/optivan/.rtl/core/rtw_tdls.o
  CC [M]  /home/optivan/.rtl/core/rtw_br_ext.o
/home/optivan/.rtl/core/rtw_br_ext.c:20:11: fatal error: net/ipx.h: Datei oder Verzeichnis nicht gefunden
   20 |  #include <net/ipx.h>
      |           ^~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /home/optivan/.rtl/core/rtw_br_ext.o] Fehler 1
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
/home/optivan/.rtl/core/rtw_mlme_ext.c: In function ‘rtw_txpwr_init_regd’:
/home/optivan/.rtl/core/rtw_mlme_ext.c:267:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
  267 |   if (rfctl->regd_name)
      |      ^
/home/optivan/.rtl/core/rtw_mlme_ext.c:270:2: note: here
  270 |  default:
      |  ^~~~~~~
/home/optivan/.rtl/core/rtw_mlme_ext.c: In function ‘mgt_dispatcher’:
/home/optivan/.rtl/core/rtw_mlme_ext.c:1379:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1379 |    ptable->func = &OnAuthClient;
      |    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/home/optivan/.rtl/core/rtw_mlme_ext.c:1381:2: note: here
 1381 |  case WIFI_ASSOCREQ:
      |  ^~~~
make[1]: *** [Makefile:1868: /home/optivan/.rtl] Fehler 2
make[1]: Verzeichnis „/usr/src/linux-headers-5.15.0-generic“ wird verlassen
make: *** [Makefile:2362: modules] Fehler 2

I May wanna ask when this is updated to Kernel 5.15 or is there allready an Update?

Regrads Optivan

**Comment by gordboy** [comment]
Not maintaining this repo any further. There are better devices and drivers.
