### ISSUE TITLE
Arch Linux Linux Kernel 5.15.1 Driver not Compiling

### ISSUE THREAD

**Issue by RusWolf76** [gordboy/rtl8812au-5.9.3.2#28]
`[wolf@wolf-arch` rtl8812au-5.9.3.2-main]$ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.15.1-arch1-2/build M=/home/wolf/rtl8812au-5.9.3.2-main  modules
make[1]: Entering directory '/usr/lib/modules/5.15.1-arch1-2/build'
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_cmd.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_security.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_debug.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_io.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_ioctl_query.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_ioctl_set.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_ieee80211.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme.o
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme.c: In function 'rtw_drv_scan_by_self':
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme.c:3157:17: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
 3157 |                 else
      |                 ^~~~
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme.c:3160:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
 3160 |                         goto exit;
      |                         ^~~~
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme_ext.o
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme_ext.c: In function 'rtw_txpwr_init_regd':
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme_ext.c:267:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
  267 |                 if (rfctl->regd_name)
      |                    ^
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme_ext.c:270:9: note: here
  270 |         default:
      |         ^~~~~~~
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme_ext.c: In function 'mgt_dispatcher':
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme_ext.c:1379:38: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1379 |                         ptable->func = &OnAuthClient;
      |                         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mlme_ext.c:1381:9: note: here
 1381 |         case WIFI_ASSOCREQ:
      |         ^~~~
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_mi.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_wlan_util.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_vht.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_pwrctrl.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_rf.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_chplan.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/monitor/rtw_radiotap.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_recv.o
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_recv.c: In function 'validate_mp_recv_frame':
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_recv.c:3598:25: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
 3598 |                         for (i = 0; i < precv_frame->u.hdr.len; i = i + 8)
      |                         ^~~
In file included from /home/wolf/rtl8812au-5.9.3.2-main/include/drv_types.h:60,
                 from /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_recv.c:17:
/home/wolf/rtl8812au-5.9.3.2-main/include/rtw_debug.h:52:33: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'for'
   52 |         #define RTW_INFO(x,...) do {} while (0)
      |                                 ^~
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_recv.c:3601:33: note: in expansion of macro 'RTW_INFO'
 3601 |                                 RTW_INFO("#############################\n");
      |                                 ^~~~~~~~
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_sta_mgt.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_ap.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/mesh/rtw_mesh.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_xmit.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_p2p.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_rson.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_tdls.o
  CC [M]  /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_br_ext.o
/home/wolf/rtl8812au-5.9.3.2-main/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>
      |                  ^~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /home/wolf/rtl8812au-5.9.3.2-main/core/rtw_br_ext.o] Error 1
make[1]: *** [Makefile:1868: /home/wolf/rtl8812au-5.9.3.2-main] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.15.1-arch1-2/build'
make: *** [Makefile:2362: modules] Error 2
[wolf@wolf-arch rtl8812au-5.9.3.2-main]$ `

**Comment by ngreve** [comment]
Same with Kernel version `5.15.2-arch1-1`

**Comment by zwangzw-zw** [comment]
From my reading, ipx is decpreated from removed from kernel 5.15

Use this driver: https://github.com/morrownr/8812au-20210629

compiled successfully on 5.15

(2/2) Install DKMS modules
==> dkms install --no-depmod rtl8812au/20210629.r56.gb001d94 -k 5.10.79-1-lts
Warning: REMAKE_INITRD has been deprecated.
==> dkms install --no-depmod rtl8812au/20210629.r56.gb001d94 -k 5.15.2-arch1-1
Warning: REMAKE_INITRD has been deprecated.
==> depmod 5.10.79-1-lts
==> depmod 5.15.2-arch1-1

**Comment by tatue64** [comment]
you need to remove ipx-support in the file "rtw_br_ext.c". See attached version of this file, which comments out the corresponding portions of the source code.


[rtw_br_ext.zip](https://github.com/gordboy/rtl8812au-5.9.3.2/files/7554204/rtw_br_ext.zip)

**Comment by mpalermo73** [comment]
> Use this driver: https://github.com/morrownr/8812au-20210629

That's the one I'm using now to get over the hump, but for whatever reason that I'm still tryign to figure out, I only get roughly half the speed and terrible stability vs this onew (`gordboys`).  I'll give you one guess when I switched to the `morrownr` version:

![Screenshot_20211215_073846](https://user-images.githubusercontent.com/847259/146191885-7473db47-bb5a-45b7-afae-461d7c0f9044.png)


```
-> % speedtest                              
Retrieving speedtest.net configuration...
Testing from Verizon Fios (xxx.xxx.xxx.xxx)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Dataspindle LLC (Somwhere, XX) [56.23 km]: 15.232 ms
Testing download speed................................................................................
Download: 168.55 Mbit/s
Testing upload speed......................................................................................................
Upload: 187.45 Mbit/s
```

The AP is literally on the other side of the plasterboard wall.  I don't have a saved output from this `gordboys` version, but this one is literally about twice that.  I don't know what the difference is that would cause that.

My only point is that while, yes right now, the `morrownr` complies and works, there's something really wonky about it...

**Comment by gordboy** [comment]
Not maintaining this repo any further. There are better devices and drivers.

**Comment by mpalermo73** [comment]
Thanks for all the work!
