### ISSUE TITLE
wifi.scan-rand-mac-address=no

### ISSUE THREAD

**Issue by morrownr** [gordboy/rtl8812au-5.9.3.2#5]
Is this still an issue? I've been using Linux since long before WiFi existed and have never run across a problem that was solved by this so any background would be appreciated. I've googled it but as best I can make out this was a temp issue caused by a specific bug that has long since been fixed and should not be a problem in distros released this year. Maybe I am wrong.

**Comment by gordboy** [comment]
Not sure. I *could* change the line to

```
As others have noted, people using NetworkManager *may* need to add this stanza ...
```

My code does not do injection or anything naughty so it does not matter much to me. I guess if you were paranoid about unknown APs you might want to have a randomized MAC. It just isn't an issue for me, and NetworkManager certainly used to have this bug, even fairly recently.

My own Dell laptop, running Ubuntu 20.04.1 with NetworkManager has this added, your mileage might vary. I should also add that I do filtering by MAC on my router (to have unchanging internal IPs but still dished out by DHCP), so randomized MAC is bad for me.

That laptop is *never, ever, ever* connected to anything else, except my home network ... so I guess you could argue that I am the paranoid one :)
